name: Build
on: 
  schedule: 
    - cron: 56 12 * * 2
  workflow_dispatch:
jobs:
  main:
    name: Fetch V2ray4.45.2 Source Code,Modify,And Build
    runs-on: ubuntu-latest
    steps: 
    - name: SetUpGoEnv
      run: |
        sudo apt install -y wget git
        wget -q https://golang.google.cn/dl/go1.18.3.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
        /usr/local/go/bin/go version
    - name: FetchAndBuild
      run: |
        wget -q -O v2ray.zip https://github.com/v2fly/v2ray-core/releases/download/v4.45.2/v2ray-linux-64.zip
        unzip v2ray.zip
        wget -q -O v2ray-core-4.45.2.tar.gz https://github.com/ioptu/buv1kdjsnet/raw/main/v2ray-core-4.45.2m.tar.gz
        tar -xvf v2ray-core-4.45.2.tar.gz
        cd ./v2ray-core-4.45.2/main/
        TS=$(date +%s)
        sed -i s/platform/$TS/g ../core.go
        env CGO_ENABLED=0 /usr/local/go/bin/go build -ldflags "-s -w"
        cd ../../ && wget -q https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        tar -xvf upx-3.96-amd64_linux.tar.xz
        cd upx-3.96-amd64_linux && ./upx -1 ../v2ray-core-4.45.2/main/main
        cd ../ && chmod 777 ./v2ray-core-4.45.2/main/main ./v2ray
        git clone https://github.com/ioptu/buv1kdjsnet.git
        cd buv1kdjsnet && git init
        mv -f ../v2ray-core-4.45.2/main/main ./v2ray.upx
        mv -f ../v2ray ./v2ray.origin
        echo "v2ray.upx sha256:$(sha256sum ./v2ray.upx)"
        echo "v2ray.origin sha256:$(sha256sum ./v2ray.origin)"
    - name: CommitAndPush
      run: |
        cd ./buv1kdjsnet
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        git add .
        git commit -m "Build By Github Actions"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/ioptu/buv1kdjsnet.git
        git push -u origin main
